[2024-04-03T08:51:34.104+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:51:34.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:51:34.110+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:51:34.110+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:51:34.118+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:51:34.117+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:51:34.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:51:34.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T08:52:04.377+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:52:04.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:52:04.383+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:52:04.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:52:04.390+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:52:04.389+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:52:04.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:52:04.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T08:52:34.827+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:52:34.829+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:52:34.833+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:52:34.832+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:52:34.841+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:52:34.839+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:52:34.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:52:34.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T08:53:04.987+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:53:04.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:53:04.994+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:53:04.993+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:53:05.002+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:53:05.000+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:53:05.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:53:05.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T08:53:35.115+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:53:35.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:53:35.122+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:53:35.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:53:35.130+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:53:35.128+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:53:35.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:53:35.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T08:54:05.480+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:54:05.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:54:05.487+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:54:05.486+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:54:05.495+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:54:05.493+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:54:05.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:54:05.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T08:54:35.823+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:54:35.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:54:35.830+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:54:35.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:54:35.837+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:54:35.836+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:54:35.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:54:35.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T08:55:06.407+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:55:06.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:55:06.413+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:55:06.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:55:06.420+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:55:06.419+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:55:06.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:55:06.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.065 seconds
[2024-04-03T08:55:36.680+0000] {processor.py:161} INFO - Started process (PID=507) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:55:36.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:55:36.688+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:55:36.687+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:55:36.696+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:55:36.694+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:55:36.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:55:36.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T08:56:07.012+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:56:07.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:56:07.020+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:56:07.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:56:07.027+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:56:07.025+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:56:07.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:56:07.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T08:56:37.864+0000] {processor.py:161} INFO - Started process (PID=623) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:56:37.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:56:37.870+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:56:37.870+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:56:37.878+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:56:37.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:56:37.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:56:37.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T08:57:08.456+0000] {processor.py:161} INFO - Started process (PID=681) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:57:08.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:57:08.463+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:57:08.462+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:57:08.472+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:57:08.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:57:08.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:57:08.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.065 seconds
[2024-04-03T08:57:38.813+0000] {processor.py:161} INFO - Started process (PID=739) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T08:57:38.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T08:57:38.819+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:57:38.818+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T08:57:38.827+0000] {logging_mixin.py:188} INFO - [2024-04-03T08:57:38.825+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T08:57:38.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T08:57:38.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T09:01:09.149+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:01:09.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:01:09.155+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:01:09.155+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:01:09.166+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:01:09.161+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:01:09.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:01:09.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.086 seconds
[2024-04-03T09:01:39.466+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:01:39.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:01:39.474+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:01:39.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:01:39.483+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:01:39.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:01:39.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:01:39.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.066 seconds
[2024-04-03T09:02:09.774+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:02:09.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:02:09.787+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:02:09.786+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:02:09.794+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:02:09.792+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:02:09.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:02:09.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.082 seconds
[2024-04-03T09:03:28.304+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:03:28.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:03:28.311+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:03:28.310+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:03:28.318+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:03:28.316+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:03:28.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:03:28.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.071 seconds
[2024-04-03T09:03:58.623+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:03:58.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:03:58.630+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:03:58.629+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:03:58.637+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:03:58.635+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:03:58.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:03:58.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:04:28.913+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:04:28.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:04:28.920+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:04:28.920+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:04:28.927+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:04:28.926+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:04:28.928+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:04:28.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:04:59.203+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:04:59.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:04:59.210+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:04:59.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:04:59.217+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:04:59.215+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:04:59.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:04:59.262+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T09:05:29.501+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:05:29.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:05:29.508+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:05:29.507+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:05:29.515+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:05:29.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:05:29.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:05:29.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:05:59.796+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:05:59.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:05:59.803+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:05:59.802+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:05:59.810+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:05:59.809+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:05:59.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:05:59.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:06:30.095+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:06:30.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:06:30.102+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:06:30.101+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:06:30.109+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:06:30.107+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:06:30.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:06:30.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:07:00.390+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:07:00.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:07:00.397+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:07:00.397+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:07:00.404+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:07:00.403+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:07:00.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:07:00.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:09:30.325+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:09:30.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:09:30.339+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:09:30.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:09:30.347+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:09:30.345+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:09:30.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:09:30.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.075 seconds
[2024-04-03T09:10:00.597+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:10:00.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:10:00.604+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:10:00.603+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:10:00.611+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:10:00.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:10:00.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:10:00.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.065 seconds
[2024-04-03T09:11:34.824+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:11:34.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:11:34.830+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:11:34.830+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:11:34.837+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:11:34.836+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:11:34.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:11:34.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.065 seconds
[2024-04-03T09:12:05.111+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:12:05.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:12:05.118+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:12:05.117+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:12:05.125+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:12:05.123+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:12:05.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:12:05.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:12:35.408+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:12:35.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:12:35.414+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:12:35.414+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:12:35.422+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:12:35.420+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:12:35.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:12:35.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T09:13:05.700+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:13:05.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:13:05.707+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:13:05.707+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:13:05.715+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:13:05.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:13:05.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:13:05.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:13:35.995+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:13:35.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:13:36.001+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:13:36.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:13:36.008+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:13:36.007+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:13:36.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:13:36.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T09:14:06.289+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:14:06.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:14:06.296+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:14:06.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:14:06.303+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:14:06.302+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:14:06.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:14:06.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:14:36.589+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:14:36.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:14:36.595+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:14:36.594+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:14:36.604+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:14:36.600+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:14:36.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:14:36.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:15:06.880+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:15:06.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:15:06.886+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:15:06.885+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:15:06.892+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:15:06.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:15:06.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:15:06.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:15:37.170+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:15:37.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:15:37.178+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:15:37.177+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:15:37.185+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:15:37.183+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:15:37.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:15:37.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.065 seconds
[2024-04-03T09:16:07.467+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:16:07.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:16:07.473+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:16:07.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:16:07.482+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:16:07.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:16:07.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:16:07.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T09:18:16.079+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:18:16.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:18:16.086+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:18:16.085+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:18:16.092+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:18:16.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:18:16.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:18:16.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.072 seconds
[2024-04-03T09:18:46.353+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:18:46.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:18:46.360+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:18:46.359+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:18:46.367+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:18:46.365+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:18:46.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:18:46.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.066 seconds
[2024-04-03T09:19:16.651+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:19:16.653+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:19:16.657+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:19:16.657+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:19:16.664+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:19:16.663+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:19:16.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:19:16.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:19:46.946+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:19:46.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:19:46.952+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:19:46.951+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:19:46.959+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:19:46.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:19:46.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:19:47.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.065 seconds
[2024-04-03T09:20:17.241+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:20:17.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:20:17.248+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:20:17.247+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:20:17.255+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:20:17.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:20:17.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:20:17.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:20:47.533+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:20:47.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:20:47.540+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:20:47.540+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:20:47.548+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:20:47.546+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:20:47.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:20:47.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T09:21:17.836+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:21:17.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:21:17.842+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:21:17.841+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:21:17.849+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:21:17.848+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:21:17.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:21:17.889+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:21:48.131+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:21:48.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:21:48.138+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:21:48.137+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:21:48.145+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:21:48.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:21:48.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:23:16.479+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:23:16.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:23:16.485+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:23:16.485+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:23:16.492+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:23:16.491+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:23:16.493+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:23:16.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:23:46.765+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:23:46.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:23:46.771+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:23:46.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:23:46.778+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:23:46.777+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:23:46.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:23:46.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.060 seconds
[2024-04-03T09:24:17.058+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:24:17.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:24:17.064+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:24:17.064+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:24:17.071+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:24:17.070+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:24:17.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:24:17.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:24:47.348+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:24:47.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:24:47.354+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:24:47.353+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:24:47.361+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:24:47.359+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:24:47.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:24:47.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:25:17.641+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:25:17.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:25:17.647+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:25:17.646+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:25:17.654+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:25:17.653+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:25:17.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:25:17.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:27:46.674+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:27:46.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:27:46.680+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:27:46.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:27:46.687+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:27:46.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:27:46.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:27:46.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.066 seconds
[2024-04-03T09:28:16.974+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:28:16.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:28:16.980+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:28:16.979+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:28:16.987+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:28:16.986+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:28:16.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:28:17.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:28:47.266+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:28:47.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:28:47.273+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:28:47.272+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:28:47.280+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:28:47.279+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:28:47.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:28:47.320+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:29:17.552+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:29:17.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:29:17.558+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:29:17.557+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:29:17.565+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:29:17.563+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:29:17.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:29:17.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:29:47.844+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:29:47.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:29:47.851+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:29:47.850+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:29:47.858+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:29:47.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:29:47.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:29:47.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:36:04.924+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:36:04.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:36:04.931+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:36:04.930+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:36:04.939+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:36:04.936+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:36:04.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:36:04.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T09:36:35.211+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:36:35.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:36:35.218+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:36:35.217+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:36:35.225+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:36:35.223+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:36:35.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:36:35.266+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:38:36.201+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:38:36.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:38:36.207+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:38:36.207+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:38:36.214+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:38:36.212+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:38:36.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:38:36.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.068 seconds
[2024-04-03T09:39:06.491+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:39:06.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:39:06.498+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:39:06.497+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:39:06.505+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:39:06.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:39:06.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:39:06.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:39:36.792+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:39:36.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:39:36.798+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:39:36.797+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:39:36.805+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:39:36.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:39:36.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:39:36.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:40:07.082+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:40:07.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:40:07.089+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:40:07.088+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:40:07.096+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:40:07.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:40:07.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:40:07.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:40:37.376+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:40:37.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:40:37.382+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:40:37.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:40:37.389+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:40:37.387+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:40:37.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:40:37.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.060 seconds
[2024-04-03T09:41:07.660+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:41:07.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:41:07.669+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:41:07.668+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:41:07.676+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:41:07.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:41:07.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:41:07.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.078 seconds
[2024-04-03T09:41:37.953+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:41:37.955+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:41:37.959+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:41:37.958+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:41:37.966+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:41:37.965+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:41:37.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:41:38.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:42:08.241+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:42:08.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:42:08.251+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:42:08.250+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:42:08.260+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:42:08.258+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:42:08.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:42:08.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.075 seconds
[2024-04-03T09:42:38.538+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:42:38.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:42:38.544+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:42:38.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:42:38.551+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:42:38.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:42:38.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:42:38.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:43:08.830+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:43:08.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:43:08.837+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:43:08.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:43:08.845+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:43:08.843+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:43:08.846+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:43:08.885+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:43:39.162+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:43:39.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:43:39.169+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:43:39.168+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:43:39.176+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:43:39.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:43:39.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:43:39.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:44:09.457+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:44:09.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:44:09.463+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:44:09.463+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:44:09.470+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:44:09.469+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:44:09.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:44:09.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:44:39.753+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:44:39.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:44:39.759+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:44:39.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:44:39.766+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:44:39.765+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:44:39.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:44:39.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:45:10.045+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:45:10.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:45:10.052+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:45:10.051+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:45:10.059+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:45:10.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:45:10.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:45:10.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.070 seconds
[2024-04-03T09:49:38.821+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:49:38.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:49:38.830+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:49:38.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:49:38.837+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:49:38.835+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:49:38.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:49:38.886+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.073 seconds
[2024-04-03T09:50:09.103+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:50:09.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:50:09.110+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:50:09.110+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:50:09.117+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:50:09.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:50:09.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:50:09.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:50:39.397+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:50:39.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:50:39.403+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:50:39.403+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:50:39.410+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:50:39.409+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:50:39.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:50:39.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.065 seconds
[2024-04-03T09:51:09.702+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:51:09.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:51:09.709+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:51:09.708+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:51:09.716+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:51:09.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:51:09.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:51:09.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:51:39.993+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:51:39.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:51:40.000+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:51:40.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:51:40.008+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:51:40.006+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:51:40.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:51:40.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T09:52:10.282+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:52:10.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:52:10.289+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:52:10.288+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:52:10.296+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:52:10.294+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:52:10.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:52:10.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:52:40.577+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:52:40.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:52:40.583+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:52:40.582+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:52:40.590+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:52:40.589+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:52:40.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:52:40.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:53:10.870+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:53:10.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:53:10.876+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:53:10.876+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:53:10.884+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:53:10.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:53:10.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:53:10.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:53:41.166+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:53:41.169+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:53:41.172+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:53:41.172+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:53:41.180+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:53:41.178+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:53:41.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:53:41.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:54:11.458+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:54:11.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:54:11.465+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:54:11.464+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:54:11.472+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:54:11.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:54:11.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:54:11.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T09:55:55.228+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:55:55.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:55:55.235+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:55:55.234+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:55:55.241+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:55:55.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:55:55.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:55:55.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T09:56:25.541+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:56:25.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:56:25.549+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:56:25.548+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:56:25.555+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:56:25.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:56:25.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:56:25.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T09:56:55.841+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:56:55.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:56:55.848+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:56:55.847+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:56:55.855+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:56:55.853+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:56:55.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:56:55.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:57:26.126+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:57:26.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:57:26.133+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:57:26.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:57:26.140+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:57:26.138+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T09:57:26.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:57:26.180+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T09:57:56.416+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:57:56.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:57:56.423+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:57:56.422+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:57:57.594+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:57:57.591+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T09:57:57.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:57:57.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 1.225 seconds
[2024-04-03T09:58:27.925+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:58:27.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:58:27.932+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:58:27.931+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:58:28.598+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:58:28.595+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T09:58:28.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:58:28.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.720 seconds
[2024-04-03T09:58:59.430+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:58:59.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:58:59.437+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:58:59.436+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:59:00.117+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:59:00.113+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T09:59:00.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:59:00.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.732 seconds
[2024-04-03T09:59:30.846+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T09:59:30.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T09:59:30.853+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:59:30.852+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T09:59:31.498+0000] {logging_mixin.py:188} INFO - [2024-04-03T09:59:31.495+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T09:59:31.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T09:59:31.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.697 seconds
[2024-04-03T10:00:02.242+0000] {processor.py:161} INFO - Started process (PID=122) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:00:02.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:00:02.249+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:00:02.248+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:00:02.256+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:00:02.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:00:02.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:00:02.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.066 seconds
[2024-04-03T10:00:32.527+0000] {processor.py:161} INFO - Started process (PID=131) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:00:32.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:00:32.534+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:00:32.533+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:00:32.542+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:00:32.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:00:32.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:00:32.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T10:01:02.840+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:01:02.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:01:02.848+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:01:02.847+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:01:02.857+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:01:02.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:01:02.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:01:02.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T10:05:20.639+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:05:20.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:05:20.646+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:05:20.645+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:05:20.654+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:05:20.652+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:05:20.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:05:20.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.058 seconds
[2024-04-03T10:05:50.878+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:05:50.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:05:50.884+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:05:50.883+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:05:50.892+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:05:50.890+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:05:50.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:05:50.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.059 seconds
[2024-04-03T10:06:21.069+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:06:21.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:06:21.075+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:06:21.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:06:21.083+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:06:21.081+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:06:21.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:06:21.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T10:06:51.276+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:06:51.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:06:51.282+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:06:51.281+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:06:51.289+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:06:51.287+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:06:51.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:06:51.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T10:07:21.473+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:07:21.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:07:21.479+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:07:21.479+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:07:21.487+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:07:21.485+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:07:21.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:07:21.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.060 seconds
[2024-04-03T10:07:51.680+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:07:51.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:07:51.686+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:07:51.685+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:07:51.694+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:07:51.692+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:07:51.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:07:51.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.073 seconds
[2024-04-03T10:08:21.880+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:08:21.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:08:21.886+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:08:21.886+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:08:21.894+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:08:21.892+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:08:21.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:08:21.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.060 seconds
[2024-04-03T10:08:52.095+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:08:52.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:08:52.100+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:08:52.100+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:08:52.108+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:08:52.107+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:08:52.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:08:52.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T10:09:22.291+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:09:22.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:09:22.297+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:09:22.297+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:09:22.305+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:09:22.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:09:22.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:09:22.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T10:09:52.500+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:09:52.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:09:52.506+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:09:52.505+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:09:52.514+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:09:52.512+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:09:52.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:09:52.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.060 seconds
[2024-04-03T10:10:22.737+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:10:22.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:10:22.742+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:10:22.742+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:10:22.750+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:10:22.748+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:10:22.751+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:10:22.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.059 seconds
[2024-04-03T10:10:52.930+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:10:52.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:10:52.937+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:10:52.936+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:10:52.945+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:10:52.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:10:52.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:10:52.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.067 seconds
[2024-04-03T10:11:23.146+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:11:23.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:11:23.152+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:11:23.152+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:11:23.160+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:11:23.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:11:23.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:11:23.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T10:11:53.343+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:11:53.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:11:53.350+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:11:53.349+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:11:53.358+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:11:53.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:11:53.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:11:53.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.060 seconds
[2024-04-03T10:12:23.558+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:12:23.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:12:23.564+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:12:23.563+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:12:23.571+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:12:23.569+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:12:23.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:12:23.611+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.060 seconds
[2024-04-03T10:12:53.749+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:12:53.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:12:53.755+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:12:53.754+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:12:53.763+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:12:53.762+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:12:53.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:12:53.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T10:13:23.962+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:13:23.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:13:23.969+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:13:23.968+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:13:23.976+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:13:23.975+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:13:23.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:13:24.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T10:13:54.159+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:13:54.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:13:54.165+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:13:54.164+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:13:54.174+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:13:54.172+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:13:54.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:13:54.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T10:14:24.370+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:14:24.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:14:24.376+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:14:24.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:14:24.385+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:14:24.383+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:14:24.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:14:24.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T10:14:54.563+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:14:54.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:14:54.570+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:14:54.569+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:14:54.577+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:14:54.576+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:14:54.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:14:54.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.061 seconds
[2024-04-03T10:28:07.424+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:28:07.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:28:07.431+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:28:07.431+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:28:07.439+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:28:07.437+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:28:07.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:28:07.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T10:28:37.675+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:28:37.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:28:37.681+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:28:37.680+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:28:37.688+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:28:37.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:28:37.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:28:37.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.059 seconds
[2024-04-03T10:29:07.875+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:07.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:29:07.882+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:29:07.881+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:07.889+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:29:07.888+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:29:07.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:07.935+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.072 seconds
[2024-04-03T10:29:38.083+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:38.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:29:38.088+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:29:38.087+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:38.096+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:29:38.094+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from config.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'config'
[2024-04-03T10:29:38.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:38.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T10:29:41.141+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:41.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:29:41.147+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:29:41.146+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:41.158+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:29:41.156+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:29:41.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:29:41.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.066 seconds
[2024-04-03T10:30:11.376+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:30:11.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:30:11.382+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:30:11.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:30:11.392+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:30:11.390+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:30:11.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:30:11.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.066 seconds
[2024-04-03T10:30:41.567+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:30:41.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:30:41.574+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:30:41.573+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:30:41.582+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:30:41.580+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:30:41.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:30:41.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.063 seconds
[2024-04-03T10:31:11.785+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:31:11.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:31:11.792+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:31:11.791+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:31:11.800+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:31:11.798+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:31:11.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:31:11.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T10:31:41.976+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:31:41.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:31:41.983+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:31:41.982+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:31:41.990+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:31:41.989+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:31:41.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:31:42.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.062 seconds
[2024-04-03T10:32:12.210+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:32:12.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:32:12.216+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:32:12.216+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:32:12.230+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:32:12.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:32:12.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:32:12.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.069 seconds
[2024-04-03T10:32:42.400+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:32:42.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:32:42.408+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:32:42.408+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:32:42.417+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:32:42.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 4, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:32:42.418+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:32:42.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.064 seconds
[2024-04-03T10:33:01.560+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:01.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:33:01.567+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:01.566+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:01.577+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:01.575+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:33:01.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:01.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.074 seconds
[2024-04-03T10:33:02.604+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:02.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:33:02.610+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:02.609+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:02.620+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:02.618+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:33:02.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:02.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.066 seconds
[2024-04-03T10:33:04.696+0000] {processor.py:161} INFO - Started process (PID=118) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:04.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:33:04.704+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:04.703+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:04.714+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:04.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 6, in <module>
    from include.homes_jp.extractors import extract_real_estate_urls, extract_real_estates
ModuleNotFoundError: No module named 'include'
[2024-04-03T10:33:04.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:04.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.081 seconds
[2024-04-03T10:33:34.928+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:34.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:33:34.934+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:34.934+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:36.100+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:36.097+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 7, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T10:33:36.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:36.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 1.219 seconds
[2024-04-03T10:33:39.210+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:39.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:33:39.216+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:39.215+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:39.881+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:33:39.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T10:33:39.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:33:39.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.718 seconds
[2024-04-03T10:34:10.143+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:34:10.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:34:10.150+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:34:10.149+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:34:10.809+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:34:10.806+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T10:34:10.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:34:10.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.713 seconds
[2024-04-03T10:34:41.043+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:34:41.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:34:41.050+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:34:41.049+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:34:41.716+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:34:41.712+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/real_estates.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/real_estates.py", line 5, in <module>
    from include.homes_jp.loaders import load_to_mongo
  File "/opt/airflow/dags/include/homes_jp/loaders/__init__.py", line 3, in <module>
    from include.homes_jp.loaders.one_c import one_c
  File "/opt/airflow/dags/include/homes_jp/loaders/one_c.py", line 7, in <module>
    def one_c(data: list[dict]):
TypeError: 'type' object is not subscriptable
[2024-04-03T10:34:41.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:34:41.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.720 seconds
[2024-04-03T10:35:11.945+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:35:11.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:35:11.951+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:11.950+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:35:12.653+0000] {processor.py:840} INFO - DAG(s) 'real_estates' retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:35:13.125+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:13.124+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:real_estates
[2024-04-03T10:35:13.402+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:13.402+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:real_estates
[2024-04-03T10:35:13.418+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:13.417+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:real_estates
[2024-04-03T10:35:13.419+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:13.418+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-03T10:35:13.442+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:13.441+0000] {dag.py:3069} INFO - Creating ORM DAG for real_estates
[2024-04-03T10:35:13.467+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:13.466+0000] {dag.py:3834} INFO - Setting next_dagrun for real_estates to 2024-04-02 00:00:00+00:00, run_after=2024-04-03 00:00:00+00:00
[2024-04-03T10:35:13.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 1.561 seconds
[2024-04-03T10:35:43.702+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/real_estates.py
[2024-04-03T10:35:43.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/real_estates.py for tasks to queue
[2024-04-03T10:35:43.709+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:43.708+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/real_estates.py
[2024-04-03T10:35:44.390+0000] {processor.py:840} INFO - DAG(s) 'real_estates' retrieved from /opt/airflow/dags/real_estates.py
[2024-04-03T10:35:44.448+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:44.447+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-03T10:35:44.502+0000] {logging_mixin.py:188} INFO - [2024-04-03T10:35:44.501+0000] {dag.py:3834} INFO - Setting next_dagrun for real_estates to 2024-04-02 00:00:00+00:00, run_after=2024-04-03 00:00:00+00:00
[2024-04-03T10:35:44.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/real_estates.py took 0.846 seconds
