[2024-04-04T09:26:29.942+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.extract_real_estate_urls manual__2024-04-04T08:47:03.043176+00:00 [queued]>
[2024-04-04T09:26:29.961+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.extract_real_estate_urls manual__2024-04-04T08:47:03.043176+00:00 [queued]>
[2024-04-04T09:26:29.962+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 6
[2024-04-04T09:26:29.990+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): extract_real_estate_urls> on 2024-04-04 08:47:03.043176+00:00
[2024-04-04T09:26:30.004+0000] {standard_task_runner.py:60} INFO - Started process 4629 to run task
[2024-04-04T09:26:30.011+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'extract_real_estate_urls', 'manual__2024-04-04T08:47:03.043176+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpgq3enw9u']
[2024-04-04T09:26:30.017+0000] {standard_task_runner.py:88} INFO - Job 232: Subtask extract_real_estate_urls
[2024-04-04T09:26:30.436+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.extract_real_estate_urls manual__2024-04-04T08:47:03.043176+00:00 [running]> on host 05a350db99a0
[2024-04-04T09:26:30.589+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='extract_real_estate_urls' AIRFLOW_CTX_EXECUTION_DATE='2024-04-04T08:47:03.043176+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-04T08:47:03.043176+00:00'
[2024-04-04T09:26:32.482+0000] {urls.py:36} INFO - Found 84763 real estates
[2024-04-04T09:26:32.488+0000] {urls.py:41} INFO - Found 2125 pages
[2024-04-04T09:26:40.443+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-04-04T09:26:40.448+0000] {process_utils.py:131} INFO - Sending 15 to group 4629. PIDs of all processes in the group: [4629]
[2024-04-04T09:26:40.450+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 4629
[2024-04-04T09:26:40.451+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-04T09:26:40.704+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=4629, status='terminated', exitcode=0, started='09:26:29') (4629) terminated with exit code 0
