[2024-04-04T07:11:12.823+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estates.extract_real_estates scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T07:11:12.843+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estates.extract_real_estates scheduled__2024-04-03T00:00:00+00:00 [queued]>
[2024-04-04T07:11:12.843+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 5
[2024-04-04T07:11:12.872+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): extract_real_estates> on 2024-04-03 00:00:00+00:00
[2024-04-04T07:11:12.887+0000] {standard_task_runner.py:60} INFO - Started process 2559 to run task
[2024-04-04T07:11:12.894+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estates', 'extract_real_estates', 'scheduled__2024-04-03T00:00:00+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/real_estates/__init__.py', '--cfg-path', '/tmp/tmpmxkzok8e']
[2024-04-04T07:11:12.900+0000] {standard_task_runner.py:88} INFO - Job 177: Subtask extract_real_estates
[2024-04-04T07:11:13.323+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estates.extract_real_estates scheduled__2024-04-03T00:00:00+00:00 [running]> on host 05a350db99a0
[2024-04-04T07:11:13.790+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estates' AIRFLOW_CTX_TASK_ID='extract_real_estates' AIRFLOW_CTX_EXECUTION_DATE='2024-04-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-03T00:00:00+00:00'
[2024-04-04T07:11:26.606+0000] {real_estates.py:29} INFO - Batch 1/3 fetched 1000 pages
[2024-04-04T07:11:54.348+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/__init__.py", line 17, in extract_real_estates
    return asyncio.run(_extract_real_estates(urls))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/real_estates.py", line 32, in _extract_real_estates
    real_estate_data = await extract_real_estate_data(response_text, url_obj)
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/real_estates.py", line 67, in extract_real_estate_data
    return {**format_2(soup), "url": url_human}
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/real_estates.py", line 132, in format_2
    real_estate_data.update(extract_from_table(table))
  File "/opt/airflow/dags/real_estates/homes_jp/extractors/real_estates.py", line 111, in extract_from_table
    trs = table.select("tbody > tr")
AttributeError: 'NoneType' object has no attribute 'select'
[2024-04-04T07:11:54.367+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=real_estates, task_id=extract_real_estates, execution_date=20240403T000000, start_date=20240404T071112, end_date=20240404T071154
[2024-04-04T07:11:54.391+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 177 for task extract_real_estates ('NoneType' object has no attribute 'select'; 2559)
[2024-04-04T07:11:54.577+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-04T07:11:54.610+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
